on:
  push:
    branches:
    - master

name: Publish Image
jobs:
  dockerpush:
    name: docker build
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2.0.0
    - 
      uses: go-semantic-release/action@v1
      id: version
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - 
      run: echo "Pushing version ${{ steps.version.outputs.version }}"
    - 
      name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.22
      with:
        registry: docker.pkg.github.com
        name: "ironpeakservices/iron-scratch/iron-scratch:${{ steps.version.outputs.version }}"
        username: hazcod
        password: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: Create GitHub release
      uses: sondreb/action-release@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
        tag: "${{ steps.version.outputs.version }}"
